version: "3.8"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg_store:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "-U",
          "${POSTGRES_USER}",
          "-d",
          "${POSTGRES_DB}",
        ]
      interval: 10s
      timeout: 30s
      retries: 5

volumes:
  pg_store:
