# Generated by Django 4.2.10 on 2024-04-01 05:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('initiator', 'receiver')},
        ),
    ]
